"""The 15 storefront templates the onboarding LLM can pick from.

Each template is a self-contained JSON-ish dict describing visual identity
(colors, typography), layout intent (hero style, grid, card style), and
suggested content slots (default categories, sample hero text). The LLM
reads the catalog via ``list_templates()`` (in onboarding tools), picks one,
and uses ``finalize_onboarding(template_id=...)`` to lock it in.

Front-end's ``<TemplateRenderer />`` is the single component that consumes
this shape — no per-template React components. To change visual behavior,
edit the JSON here, not React.

Edit guidance:
- Keep `template_id` immutable once a store is published with it.
- `industry_keywords` are matched substring-style against the trader's
  business description; lowercase tokens.
- Hex colors should pair: ensure `primary_color` text on `background` and
  on `card_background` clears AA contrast.
- `sections` array drives section order in the renderer.
"""
from __future__ import annotations

from typing import Any


def _t(
    template_id: str,
    name: str,
    tagline: str,
    best_for: list[str],
    industry_keywords: list[str],
    vibe: str,
    theme: dict[str, str],
    typography: dict[str, str],
    layout: dict[str, Any],
    default_categories: list[str],
    sample_hero_text: str,
    cta_label: str = "Shop now",
    sections: list[str] | None = None,
) -> dict[str, Any]:
    """Helper to keep template dicts compact and consistent."""
    return {
        "template_id": template_id,
        "name": name,
        "tagline": tagline,
        "best_for": best_for,
        "industry_keywords": industry_keywords,
        "vibe": vibe,
        "theme": theme,
        "typography": typography,
        "layout": layout,
        "default_categories": default_categories,
        "sample_hero_text": sample_hero_text,
        "cta_label": cta_label,
        "sections": sections or ["hero", "featured_products", "all_products", "about", "footer"],
    }


TEMPLATES: list[dict[str, Any]] = [
    _t(
        "lagos_boutique",
        "Lagos Boutique",
        "Warm earth tones with editorial photography for fashion and lace traders.",
        ["fashion", "boutique", "lace", "ankara wear", "ready-to-wear"],
        ["boutique", "lace", "ankara", "ready to wear", "dress", "skirt", "blouse"],
        "warm, editorial, hand-crafted",
        {
            "primary_color": "#7C2D12",
            "accent_color": "#F59E0B",
            "background": "#FAF8F5",
            "card_background": "#FFFFFF",
            "text_color": "#1C1917",
            "muted_text": "#78716C",
            "border_color": "#E7E5E4",
            "hero_gradient": "linear-gradient(135deg, #7C2D12 0%, #A16207 100%)",
        },
        {"heading_font": "serif", "body_font": "sans", "heading_weight": "semibold"},
        {
            "hero_style": "editorial_split",
            "product_grid": "2-col",
            "card_style": "warm",
            "show_search": True,
            "show_categories": True,
            "show_sort": True,
            "show_about_section": True,
        },
        ["New In", "Dresses", "Accessories", "Sale"],
        "Handcrafted ankara and lace, delivered across Lagos.",
    ),
    _t(
        "naija_streetwear",
        "Naija Streetwear",
        "Bold yellow and black magazine layout for streetwear and bold fashion.",
        ["streetwear", "tees", "hoodies", "sneakers", "youth fashion"],
        ["streetwear", "tee", "hoodie", "sneaker", "swag", "drip"],
        "bold, energetic, magazine-style",
        {
            "primary_color": "#000000",
            "accent_color": "#FACC15",
            "background": "#FFFFFF",
            "card_background": "#FAFAFA",
            "text_color": "#000000",
            "muted_text": "#525252",
            "border_color": "#E5E5E5",
            "hero_gradient": "linear-gradient(135deg, #000000 0%, #1F1F1F 100%)",
        },
        {"heading_font": "display", "body_font": "sans", "heading_weight": "black"},
        {
            "hero_style": "magazine_block",
            "product_grid": "3-col",
            "card_style": "flat",
            "show_search": True,
            "show_categories": True,
            "show_sort": True,
            "show_about_section": False,
        },
        ["Drops", "Tees", "Hoodies", "Sneakers"],
        "New drops every Friday. Lagos-made streetwear.",
        cta_label="Cop it",
    ),
    _t(
        "ankara_artisan",
        "Ankara Artisan",
        "Vibrant orange and purple, perfect for ankara fabric and crafted accessories.",
        ["ankara", "fabric", "bags", "headwraps", "artisan"],
        ["ankara", "fabric", "gele", "bag", "headwrap", "artisan", "craft"],
        "vibrant, artisanal, celebratory",
        {
            "primary_color": "#9333EA",
            "accent_color": "#EA580C",
            "background": "#FEF3F2",
            "card_background": "#FFFFFF",
            "text_color": "#1E1B4B",
            "muted_text": "#6B7280",
            "border_color": "#FECDD3",
            "hero_gradient": "linear-gradient(135deg, #9333EA 0%, #EA580C 100%)",
        },
        {"heading_font": "serif", "body_font": "sans", "heading_weight": "bold"},
        {
            "hero_style": "full_bleed",
            "product_grid": "3-col",
            "card_style": "elevated",
            "show_search": True,
            "show_categories": True,
            "show_sort": False,
            "show_about_section": True,
        },
        ["Fabric Yards", "Bags", "Headwraps", "Accessories"],
        "Handcrafted ankara goods, made with love in Aba.",
    ),
    _t(
        "velvet_atelier",
        "Velvet Atelier",
        "Black and gold luxury layout for premium fashion and accessories.",
        ["luxury", "premium", "atelier", "couture", "jewelry"],
        ["luxury", "couture", "atelier", "premium", "jewelry", "designer"],
        "luxurious, minimal, high-end",
        {
            "primary_color": "#0A0A0A",
            "accent_color": "#D4AF37",
            "background": "#F5F5F4",
            "card_background": "#FFFFFF",
            "text_color": "#0A0A0A",
            "muted_text": "#737373",
            "border_color": "#E5E5E5",
            "hero_gradient": "linear-gradient(135deg, #0A0A0A 0%, #1F1F1F 100%)",
        },
        {"heading_font": "serif", "body_font": "serif", "heading_weight": "semibold"},
        {
            "hero_style": "minimal_centered",
            "product_grid": "2-col",
            "card_style": "outlined",
            "show_search": True,
            "show_categories": True,
            "show_sort": True,
            "show_about_section": True,
        },
        ["The Collection", "Bespoke", "Accessories"],
        "Bespoke pieces, made to your measurements.",
        cta_label="Reserve",
    ),
    _t(
        "computer_village_tech",
        "Computer Village Tech",
        "Electric blue, dense grid layout for phones, laptops, and accessories.",
        ["phones", "laptops", "electronics", "computer accessories"],
        ["phone", "laptop", "pc", "computer", "gadget", "iphone", "samsung", "macbook"],
        "trustworthy, technical, dense",
        {
            "primary_color": "#1E40AF",
            "accent_color": "#06B6D4",
            "background": "#F8FAFC",
            "card_background": "#FFFFFF",
            "text_color": "#0F172A",
            "muted_text": "#64748B",
            "border_color": "#E2E8F0",
            "hero_gradient": "linear-gradient(135deg, #1E40AF 0%, #0EA5E9 100%)",
        },
        {"heading_font": "sans", "body_font": "sans", "heading_weight": "bold"},
        {
            "hero_style": "tech_grid",
            "product_grid": "4-col",
            "card_style": "flat",
            "show_search": True,
            "show_categories": True,
            "show_sort": True,
            "show_about_section": False,
        },
        ["Smartphones", "Laptops", "Accessories", "Audio"],
        "Original phones and laptops from Computer Village, Ikeja.",
    ),
    _t(
        "phone_accessories",
        "Phone Accessories Hub",
        "Cyan accents with a tight product grid for chargers, cases and audio.",
        ["accessories", "chargers", "cases", "earbuds", "cables"],
        ["accessory", "charger", "case", "earbud", "cable", "screen protector", "powerbank"],
        "fast, utilitarian, value-focused",
        {
            "primary_color": "#0E7490",
            "accent_color": "#F97316",
            "background": "#F0FDFA",
            "card_background": "#FFFFFF",
            "text_color": "#134E4A",
            "muted_text": "#64748B",
            "border_color": "#CCFBF1",
            "hero_gradient": "linear-gradient(135deg, #0E7490 0%, #06B6D4 100%)",
        },
        {"heading_font": "sans", "body_font": "sans", "heading_weight": "bold"},
        {
            "hero_style": "full_bleed",
            "product_grid": "4-col",
            "card_style": "flat",
            "show_search": True,
            "show_categories": True,
            "show_sort": True,
            "show_about_section": False,
        },
        ["Chargers", "Cases", "Audio", "Cables", "Power"],
        "Genuine accessories. Same-day Lagos delivery.",
    ),
    _t(
        "tech_repair_hub",
        "Tech Repair Hub",
        "Steel grey, service-block layout for repair shops and diagnostics.",
        ["repairs", "diagnostics", "tech service"],
        ["repair", "fix", "diagnostic", "service", "iphone repair", "screen replacement"],
        "trustworthy, service-led, professional",
        {
            "primary_color": "#1F2937",
            "accent_color": "#10B981",
            "background": "#F9FAFB",
            "card_background": "#FFFFFF",
            "text_color": "#111827",
            "muted_text": "#6B7280",
            "border_color": "#E5E7EB",
            "hero_gradient": "linear-gradient(135deg, #1F2937 0%, #374151 100%)",
        },
        {"heading_font": "sans", "body_font": "sans", "heading_weight": "bold"},
        {
            "hero_style": "service_blocks",
            "product_grid": "2-col",
            "card_style": "outlined",
            "show_search": False,
            "show_categories": True,
            "show_sort": False,
            "show_about_section": True,
        },
        ["Screen Repair", "Battery", "Diagnostics", "Software"],
        "Same-day repairs. 90-day warranty on every job.",
        cta_label="Book a repair",
    ),
    _t(
        "mama_kitchen",
        "Mama's Kitchen",
        "Warm Nigerian palette for home cooks and meal vendors.",
        ["food", "meals", "home cooking", "catering"],
        ["food", "meal", "kitchen", "jollof", "stew", "soup", "lunch", "dinner"],
        "homely, appetising, generous",
        {
            "primary_color": "#15803D",
            "accent_color": "#DC2626",
            "background": "#FEFCE8",
            "card_background": "#FFFFFF",
            "text_color": "#1C1917",
            "muted_text": "#78716C",
            "border_color": "#FDE68A",
            "hero_gradient": "linear-gradient(135deg, #15803D 0%, #EA580C 50%, #DC2626 100%)",
        },
        {"heading_font": "serif", "body_font": "sans", "heading_weight": "bold"},
        {
            "hero_style": "menu_banner",
            "product_grid": "2-col",
            "card_style": "warm",
            "show_search": True,
            "show_categories": True,
            "show_sort": False,
            "show_about_section": True,
        },
        ["Main Dishes", "Sides", "Drinks", "Combo Packs"],
        "Home-cooked meals, delivered hot across Surulere.",
        cta_label="Order now",
    ),
    _t(
        "food_truck",
        "Food Truck",
        "Punchy orange menu layout for snacks, drinks and quick eats.",
        ["snacks", "small chops", "shawarma", "drinks"],
        ["snack", "shawarma", "small chops", "puff puff", "smoothie", "drink", "truck"],
        "punchy, energetic, quick-service",
        {
            "primary_color": "#EA580C",
            "accent_color": "#FACC15",
            "background": "#FFF7ED",
            "card_background": "#FFFFFF",
            "text_color": "#7C2D12",
            "muted_text": "#9A3412",
            "border_color": "#FED7AA",
            "hero_gradient": "linear-gradient(135deg, #EA580C 0%, #FACC15 100%)",
        },
        {"heading_font": "display", "body_font": "sans", "heading_weight": "black"},
        {
            "hero_style": "menu_banner",
            "product_grid": "3-col",
            "card_style": "elevated",
            "show_search": True,
            "show_categories": True,
            "show_sort": False,
            "show_about_section": False,
        },
        ["Snacks", "Shawarma", "Smoothies", "Combos"],
        "Hot snacks. Cold drinks. Lagos street food, anytime.",
    ),
    _t(
        "provision_store",
        "Provision Store",
        "Utility green dense grid for foodstuffs, groceries and provisions.",
        ["provisions", "foodstuff", "groceries", "rice", "oil"],
        ["provision", "foodstuff", "grocery", "rice", "oil", "garri", "beans", "market"],
        "trustworthy, dense, value-focused",
        {
            "primary_color": "#166534",
            "accent_color": "#CA8A04",
            "background": "#F7FEE7",
            "card_background": "#FFFFFF",
            "text_color": "#14532D",
            "muted_text": "#52525B",
            "border_color": "#D9F99D",
            "hero_gradient": "linear-gradient(135deg, #166534 0%, #65A30D 100%)",
        },
        {"heading_font": "sans", "body_font": "sans", "heading_weight": "bold"},
        {
            "hero_style": "full_bleed",
            "product_grid": "4-col",
            "card_style": "flat",
            "show_search": True,
            "show_categories": True,
            "show_sort": True,
            "show_about_section": False,
        },
        ["Grains", "Oil & Cooking", "Drinks", "Toiletries", "Snacks"],
        "Family provisions at market prices. Bulk discounts available.",
    ),
    _t(
        "sapphire_beauty",
        "Sapphire Beauty",
        "Rose gold soft-card layout for cosmetics, skincare and beauty.",
        ["beauty", "skincare", "cosmetics", "makeup"],
        ["beauty", "skincare", "cosmetic", "makeup", "perfume", "fragrance", "lipstick"],
        "soft, feminine, premium",
        {
            "primary_color": "#9D174D",
            "accent_color": "#F0ABFC",
            "background": "#FDF2F8",
            "card_background": "#FFFFFF",
            "text_color": "#500724",
            "muted_text": "#9F1239",
            "border_color": "#FBCFE8",
            "hero_gradient": "linear-gradient(135deg, #9D174D 0%, #F472B6 100%)",
        },
        {"heading_font": "serif", "body_font": "sans", "heading_weight": "semibold"},
        {
            "hero_style": "minimal_centered",
            "product_grid": "3-col",
            "card_style": "elevated",
            "show_search": True,
            "show_categories": True,
            "show_sort": True,
            "show_about_section": True,
        },
        ["Skincare", "Makeup", "Fragrance", "Hair", "Tools"],
        "Glow-up essentials, curated for melanin-rich skin.",
    ),
    _t(
        "wellness_studio",
        "Wellness Studio",
        "Sage green calm layout for fitness, wellness and supplements.",
        ["fitness", "wellness", "supplements", "yoga"],
        ["fitness", "wellness", "supplement", "yoga", "gym", "protein", "vitamin"],
        "calm, holistic, premium",
        {
            "primary_color": "#4D7C0F",
            "accent_color": "#0EA5E9",
            "background": "#F7FAF7",
            "card_background": "#FFFFFF",
            "text_color": "#1F2937",
            "muted_text": "#6B7280",
            "border_color": "#D1FAE5",
            "hero_gradient": "linear-gradient(135deg, #4D7C0F 0%, #84CC16 100%)",
        },
        {"heading_font": "sans", "body_font": "sans", "heading_weight": "semibold"},
        {
            "hero_style": "editorial_split",
            "product_grid": "3-col",
            "card_style": "outlined",
            "show_search": True,
            "show_categories": True,
            "show_sort": True,
            "show_about_section": True,
        },
        ["Supplements", "Equipment", "Apparel", "Programs"],
        "Movement, mindfulness and supplements for the long game.",
    ),
    _t(
        "books_and_stationery",
        "Books & Stationery",
        "Academic burgundy layout for booksellers and stationery shops.",
        ["books", "stationery", "school supplies"],
        ["book", "stationery", "novel", "textbook", "school", "pen", "notebook"],
        "academic, intellectual, organised",
        {
            "primary_color": "#7F1D1D",
            "accent_color": "#CA8A04",
            "background": "#FEF3C7",
            "card_background": "#FFFFFF",
            "text_color": "#1F2937",
            "muted_text": "#78716C",
            "border_color": "#FDE68A",
            "hero_gradient": "linear-gradient(135deg, #7F1D1D 0%, #B91C1C 100%)",
        },
        {"heading_font": "serif", "body_font": "serif", "heading_weight": "semibold"},
        {
            "hero_style": "editorial_split",
            "product_grid": "3-col",
            "card_style": "warm",
            "show_search": True,
            "show_categories": True,
            "show_sort": True,
            "show_about_section": True,
        },
        ["New Releases", "African Lit", "Textbooks", "Stationery"],
        "Books and supplies for curious minds, all year round.",
    ),
    _t(
        "bouquet_florist",
        "Bouquet Florist",
        "Pastel pink gallery layout for florists, gift shops and event vendors.",
        ["flowers", "gifts", "events", "florist"],
        ["flower", "florist", "bouquet", "gift", "event", "wedding", "anniversary"],
        "romantic, gentle, gift-focused",
        {
            "primary_color": "#831843",
            "accent_color": "#F472B6",
            "background": "#FDF2F8",
            "card_background": "#FFFFFF",
            "text_color": "#500724",
            "muted_text": "#9F1239",
            "border_color": "#FBCFE8",
            "hero_gradient": "linear-gradient(135deg, #831843 0%, #FB7185 100%)",
        },
        {"heading_font": "serif", "body_font": "serif", "heading_weight": "semibold"},
        {
            "hero_style": "portfolio_grid",
            "product_grid": "3-col",
            "card_style": "elevated",
            "show_search": True,
            "show_categories": True,
            "show_sort": False,
            "show_about_section": True,
        },
        ["Bouquets", "Single Stems", "Gift Sets", "Event Packages"],
        "Hand-tied bouquets, delivered fresh across Abuja.",
    ),
    _t(
        "creator_portfolio",
        "Creator Portfolio",
        "Minimal monochrome portfolio for designers, photographers and service creators.",
        ["creator", "designer", "photographer", "consultant", "services"],
        ["creator", "design", "photo", "video", "consult", "service", "freelance", "course"],
        "minimal, refined, portfolio-led",
        {
            "primary_color": "#18181B",
            "accent_color": "#0EA5E9",
            "background": "#FAFAFA",
            "card_background": "#FFFFFF",
            "text_color": "#09090B",
            "muted_text": "#71717A",
            "border_color": "#E4E4E7",
            "hero_gradient": "linear-gradient(135deg, #18181B 0%, #3F3F46 100%)",
        },
        {"heading_font": "sans", "body_font": "sans", "heading_weight": "semibold"},
        {
            "hero_style": "minimal_centered",
            "product_grid": "2-col",
            "card_style": "flat",
            "show_search": False,
            "show_categories": True,
            "show_sort": False,
            "show_about_section": True,
        },
        ["Services", "Digital Products", "Bookings", "Case Studies"],
        "Services, courses and digital goods. Made for your growth.",
        cta_label="Book a slot",
    ),
]


# ---- Lookup helpers --------------------------------------------------------
_BY_ID: dict[str, dict[str, Any]] = {t["template_id"]: t for t in TEMPLATES}


def list_templates() -> list[dict[str, Any]]:
    """Return all templates as a plain list. JSON-serialisable."""
    return TEMPLATES


def get_template(template_id: str) -> dict[str, Any] | None:
    """Return a single template by id, or None if not found."""
    return _BY_ID.get(template_id)


def template_metadata_for_llm() -> list[dict[str, Any]]:
    """Compact list for LLM context — drops the heavy theme blob to save tokens."""
    return [
        {
            "template_id": t["template_id"],
            "name": t["name"],
            "tagline": t["tagline"],
            "best_for": t["best_for"],
            "vibe": t["vibe"],
        }
        for t in TEMPLATES
    ]
